name = "Mod"
filename = "mod.jar"
side = "both"

[download]
mode = "metadata:curseforge"
hash-format = "sha1"
hash = "0000000000000000000000000000000000000000"

[update]
[update.curseforge]
file-id = "9999999"
project-id = "999999"
