name = "Mod"
filename = "mod.jar"
side = "both"

[download]
url = "https://cdn.example.com/mod/mod.jar"
hash-format = "sha1"
hash = "0000000000000000000000000000000000000000"

[update]
[update.modrinth]
mod-id = "aaaaaaaa"
version = "aaaaaaaa"

[option]
description = "description"
default = true
